[package]
name = "komorebi-switcher"
description = "Minimal workspaces switcher for the komorebi tiling window manager that works in the native Windows taskbar."
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
winit = "0.30"
raw-window-handle = "0.6"
egui = "0.31"
egui-winit = "0.31"
egui-wgpu = "0.31"
wgpu = "24.0"
pollster = "0.4"
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi", tag = "v0.1.31" }
serde_json = "1.0"

[dependencies.windows]
version = "0.59"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_LibraryLoader",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
]
