[package]
name = "komorebi-switcher"
description = "A minimal workspace switcher for the Komorebi tiling window manager, seamlessly integrated into the Windows 10/11 taskbar."
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
winit = "0.30"
raw-window-handle = "0.6"
egui = "0.31"
egui-winit = "0.31"
egui-wgpu = "0.31"
wgpu = "24.0"
pollster = "0.4"
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi", tag = "v0.1.31" }
serde_json = "1.0"

[dependencies.windows]
version = "0.59"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_LibraryLoader",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_Input_KeyboardAndMouse",
]
