name: fmt

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

  taplo:
    name: taplo (.toml files)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: install taplo-cli
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - run: taplo fmt --check --diff
